<a href="https://colab.research.google.com/github/SigmaMale0510/Python-Libraries/blob/python/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# 1. Creating Arrays
print("1. Creating Arrays:")
a = np.array([1, 2, 3, 4, 5])  # 1D array
print("1D Array:", a)

b = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print("2D Array:\n", b)

1. Creating Arrays:
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# 2. Array Properties
print("\n2. Array Properties:")
print("Shape of b:", b.shape)
print("Dimensions of b:", b.ndim)
print("Size of b:", b.size)
print("Data type of elements in b:", b.dtype)



2. Array Properties:
Shape of b: (2, 3)
Dimensions of b: 2
Size of b: 6
Data type of elements in b: int64


In [7]:
# 3. Array Creation Functions
print("\n3. Array Creation Functions:")
zeros = np.zeros((2, 3))  # Array of zeros
print("Zeros Array:\n", zeros)

ones = np.ones((3, 2))  # Array of ones
print("Ones Array:\n", ones)

identity = np.eye(3)  # Identity matrix
print("Identity Matrix:\n", identity)


3. Array Creation Functions:
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# 4. Array Manipulation
print("\n4. Array Manipulation:")
flattened = b.flatten()  # Flatten the 2D array into 1D
print("Flattened Array:", flattened)

reshaped = b.reshape((3, 2))  # Reshape 2D array to another shape
print("Reshaped Array:\n", reshaped)



4. Array Manipulation:
Flattened Array: [1 2 3 4 5 6]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
# 5. Mathematical Operations
print("\n5. Mathematical Operations:")
sum_array = np.sum(b)  # Sum of all elements
print("Sum of elements in b:", sum_array)

mean_array = np.mean(b)  # Mean of all elements
print("Mean of elements in b:", mean_array)

max_value = np.max(b)  # Maximum value
print("Maximum value in b:", max_value)

min_value = np.min(b)  # Minimum value
print("Minimum value in b:", min_value)


5. Mathematical Operations:
Sum of elements in b: 21
Mean of elements in b: 3.5
Maximum value in b: 6
Minimum value in b: 1


In [12]:
# 6. Array Indexing and Slicing
print("\n6. Array Indexing and Slicing:")
print("Element at (1, 2):", b[1, 2])        # Accessing a specific element

print("Slicing first two rows:\n", b[:2])   # Slicing rows


6. Array Indexing and Slicing:
Element at (1, 2): 6
Slicing first two rows:
 [[1 2 3]
 [4 5 6]]


In [13]:
# 7. Mathematical Functions
print("\n7. Mathematical Functions:")
sqrt_array = np.sqrt(b)  # Element-wise square root
print("Square root of b:\n", sqrt_array)

log_array = np.log(b)  # Element-wise natural logarithm
print("Natural log of b:\n", log_array)


7. Mathematical Functions:
Square root of b:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Natural log of b:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [14]:
# 8. Linear Algebra
print("\n8. Linear Algebra:")
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

dot_product = np.dot(c, d)  # Matrix multiplication
print("Dot product of c and d:\n", dot_product)

eigenvalues, eigenvectors = np.linalg.eig(c)  # Eigenvalues and eigenvectors
print("Eigenvalues of c:", eigenvalues)
print("Eigenvectors of c:\n", eigenvectors)



8. Linear Algebra:
Dot product of c and d:
 [[19 22]
 [43 50]]
Eigenvalues of c: [-0.37228132  5.37228132]
Eigenvectors of c:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [15]:
# 9. Random Numbers
print("\n9. Random Numbers:")
random_array = np.random.rand(3, 3)  # Array of random numbers
print("Random Array:\n", random_array)

random_integers = np.random.randint(0, 10, size=(2, 5))  # Array of random integers
print("Random Integers Array:\n", random_integers)


9. Random Numbers:
Random Array:
 [[0.65572961 0.91910821 0.73245443]
 [0.57251187 0.73052044 0.77184453]
 [0.97988242 0.39734348 0.78745704]]
Random Integers Array:
 [[5 7 9 2 9]
 [8 5 7 2 2]]


In [16]:
# 10. Saving and Loading Arrays
print("\n10. Saving and Loading Arrays:")
np.save('array.npy', b)  # Save array to file
loaded_array = np.load('array.npy')  # Load array from file
print("Loaded Array:\n", loaded_array)


10. Saving and Loading Arrays:
Loaded Array:
 [[1 2 3]
 [4 5 6]]
